---
- name: Create tomcat group
  group:
    name: tomcat
    
- name: Create tomcat user 
  user:
    name: tomcat
    group: tomcat
    create_home: false
    
- name: Download Tomcat
  get_url:
    url: "{{ tomcat_URL }}"
    dest: /opt/
    
- name: Unarchive tomcat downloaded file
  unarchive:
    src: "/opt/{{ tomcat_dowloaded_file }}"
    dest: /opt/
    owner: tomcat
    group: tomcat
    remote_src: yes

- name: Create tomcat link
  file:
    src: "/opt/{{ tomcat_ver_dir }}"
    dest: "{{ tomcat_home }}"
    owner: tomcat
    group: tomcat
    state: link
    force: yes
 
- name: Change ownership of Tomcat installation
  file:
    path: "{{ tomcat_home }}" 
    owner: tomcat 
    group: tomcat
    state: directory
    recurse: yes

- name: copy tomcat init script file
  copy:
    src: tomcat-initscript.sh
    dest: /etc/init.d/tomcat
    mode: 0755

- name: start tomcat service
  service:
    name: tomcat
    state: started
    enabled: yes
